module.exports = Object.freeze({
  PLAN_NOT_FOUND: 1,
  USER_NOT_FOUND: 2,
  USER_ALREADY_EXISTS: 3,
  DUPLICATE_KEY: 4,
  INVALID_ID: 5,
  INVALID_DATE: 6,
  INVALID_NAME: 7,
  INVALID_EMAIL_OR_PASSWORD: 8,
  INVALID_OR_EXPIRED_TOKEN: 9,
  MONGOOSE_VALIDATION_ERROR: 10,
  MONGOOSE_CAST_ERROR: 11,
  FAILED_TO_SEND_EMAIL: 12,
  INVALID_RESET_TOKEN: 13,
  RESET_TOKEN_EXPIRED: 14,
  PASSWORD_CONFIRMATION_ERROR: 14,
  INTERNAL_SERVER_ERROR: 99,
});

